services:
  mongodb:
    image: mongo:latest  # Use the official MongoDB image from Docker Hub
    container_name: mongodb_container  # Name of the container
    ports:
      - "27017:27017"  # Map the MongoDB port 27017 to the host